### ISSUE TITLE
Update @types/ansi-colors

### ISSUE THREAD

**Issue by MurhafSousli** [doowb/ansi-colors#10]
It seems `@types/ansi-colors` is not up to date.

![image](https://user-images.githubusercontent.com/8130692/40581898-4ec853d2-616d-11e8-8282-105c34825951.png)

**Comment by doowb** [comment]
I don't maintain `@types/ansi-colors`.

There's a types file in this repo and an [issue](#9) was already open. If you'd like to submit a PR to update the file with the latest types, please do.
