### ISSUE TITLE
Bug when nesting colors causing styles to not be applied

### ISSUE THREAD

**Issue by millaisnick** [doowb/ansi-colors#17]
I got into a situation where I need to nest color styles and didn't get the result I was expecting. I wasn't sure how to fix it, so I'm just creating a bug ticket. You can reproduce it running the code below here.

```js
const c = require("ansi-colors")
console.log(c.red(`R${c.green(`G${c.blue("B")}G`)}R`))
```

![](https://user-images.githubusercontent.com/16856667/44299204-91837480-a32c-11e8-9518-268fb8ce8dac.png)

Thanks.

**Comment by doowb** [comment]
Thanks for the issue and the example, it makes it easy to see what's happening.

I know what needs to be fixed and should have a patch published shortly.

**Comment by doowb** [comment]
@millaisnick 3.0.1 has been published with the fix. Let me know if you have any other issues.

**Comment by millaisnick** [comment]
@doowb Superb! Could you update the benchmarks too please? 👏

**Comment by jonschlinkert** [comment]
> Could you update the benchmarks too please?

done! I just pushed up new benchmarks for mac and windows. Kleur and turbocolor were removed from the benchmarks since they fail too many unit tests to have parity.
