### ISSUE TITLE
Nested Colors example does not work

### ISSUE THREAD

**Issue by PjotrB** [doowb/ansi-colors#19]
Both locally and online with RunKit, this example does not work:

```
var c = require("ansi-colors")
c.yellow('foo', c.red.bold('red'), 'bar', c.cyan('cyan'), 'baz')

```
It only produces **foo** in yellow.

**Comment by doowb** [comment]
@PjotrB thanks for the issue. I'll get the readme updated since that API is no longer valid in versions `>=3.0.0`.

You can achieve that using template strings directly:

```js
c.yellow(`foo ${c.red.bold('red')} bar ${c.cyan('cyan')} baz`);
```

**Comment by jonschlinkert** [comment]
this is correct. The readme might need to be updated to show that ansi-colors only takes one argument.  thanks for the issue
