### ISSUE TITLE
Document Windows support

### ISSUE THREAD

**Issue by demurgos** [doowb/ansi-colors#2]
Hi,
Could you add a sentence in the README explaining if this library works with Windows (or other platforms that do not support ANSI escape codes)? After a quick code overview, it seems that it does not perform any detection logic and just uses the ANSI codes. Does it work with Windows?

**Comment by doowb** [comment]
This library used to require our other `ansi-*` libraries as dependencies. Those use the `ansi-wrap` library that this one uses now and some of those are used directly in other CLI applications. We haven't received any issues regarding the ANSI codes not working on windows.

I'll be able to take a closer look today or tomorrow when I have a windows machine in front of me.

**Comment by demurgos** [comment]
Thanks.
I don't have a Windows machine either: I don't know if I can safely use this plugin instead of chalk.

**Comment by doowb** [comment]
I ran the example on a windows 10 machine in the command prompt and the colors were output as expected.

If you use `ansi-colors` and run into bugs or errors, please feel free to open issues with a description on how to replicate the bug.
