### ISSUE TITLE
usage section doesn't really explain how to use

### ISSUE THREAD

**Issue by giladgray** [doowb/ansi-colors#3]
what is the type of this `colors` object? and all these color functions, how do i use them? would like to know without having to run the code. (sure this info is out there somewhere, but it absolutely belongs in README as well.)

**Comment by doowb** [comment]
There are code comments with examples on how to use the `colors` object. I'll update the readme with that information.

**Comment by doowb** [comment]
I've updated the usage section to provide more information and an example using the `colors` object, the functions, and the output from usage with `console.log`.

**Comment by giladgray** [comment]
Yes! Looks great! Thanks @doowb!
