### ISSUE TITLE
Failing CI (AppVeyor)

### ISSUE THREAD

**Issue by DanielRuf** [doowb/ansi-colors#31]
https://ci.appveyor.com/project/doowb/ansi-colors/builds/22779470

**Comment by doowb** [comment]
This project is using travis-ci for all operating systems and the windows tests are passing there. I'm not able to access that link so you'll have to provide more information on the bug you see than just a link.

**Comment by DanielRuf** [comment]
Hi, see the CI status on the repo and last commit.

![image](https://user-images.githubusercontent.com/827205/56869445-259bf480-6a01-11e9-8066-cf4377aa5c7e.png)

**Comment by DanielRuf** [comment]
> It's not an actual failure and the tests are passing for Windows on Travis-CI.

Ok, thanks for the clarification.
