### ISSUE TITLE
TypeScript Typings

### ISSUE THREAD

**Issue by Silic0nS0ldier** [doowb/ansi-colors#4]
This is just a 'nice-to-have' request, since [DefinitelyTyped](https://www.npmjs.com/package/@types/ansi-colors) has already got this covered.
Having it directly in the library would eliminate the need for a triple slash directive and another dependency for people using TypeScript. (similar argument for people using Flow I guess).

**Comment by jonschlinkert** [comment]
A pull request for typings would be great!

**Comment by doowb** [comment]
This has been published to NPM as 1.1.0.
