### ISSUE TITLE
NO_COLOR environment variable support

### ISSUE THREAD

**Issue by ed789d0** [doowb/ansi-colors#46]
See https://no-color.org/ (basically the idea is to disable color when the NO_COLOR environment variable is present.)

**Comment by mercuriete** [comment]
is this project abandoned?

the author accepts PR?

I would like to see this feature request done.

thanks for your amazing work.

**Comment by doowb** [comment]
`ansi-colors` already has way to "disable color" using the `enabled` flag. See the [README.md documentation](https://github.com/doowb/ansi-colors#toggle-color-support) for more information.

This is exposed as a way for implementors to choose how they implement disabling colors, which allows extending functionality when something new (like `NO_COLORS`) comes along.
