### ISSUE TITLE
What were the breaking changes, if any, in v4?

### ISSUE THREAD

**Issue by MatthewHerbst** [doowb/ansi-colors#48]
There is no CHANGELOG/HISTORY file, and the releases have no information. A major semver version change implies there were breaking changes. Could you please let us know what those were? Thank you

**Comment by jonschlinkert** [comment]
> A major semver version change implies there were breaking changes

No it doesn't. When there are breaking changes, a major version bump should be used, but a major version bump may be used for other reasons. 

> Could you please let us know what those were?

If there were, we would.

**Comment by MatthewHerbst** [comment]
@jonschlinkert from the [semver spec](https://semver.org/) used [by npm](https://github.com/npm/node-semver):

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> 1. MAJOR version when you make incompatible API changes,
> 2. MINOR version when you add functionality in a backwards compatible manner, and
> 3. PATCH version when you make backwards compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

To be fair, later in the spec they expand on that a bit, and they don't explicitly say you can't change the major version even without a breaking change:

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY also include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

Anyways, you're going to confuse the heck out of lots of people, and waste your time and others (as this issue has shown) by not documenting changes (or the lack thereof) when changing the major version.

Thanks for helping maintain this otherwise excellent package!
